#! /bin/sh
#
# ejabberd        Start/stop ejabberd server
#

### BEGIN INIT INFO
# Provides:          ejabberd
# Required-Start:    $local_fs $network $named $time
# Required-Stop:     $local_fs $network $named $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts ejabberd jabber server
# Description:       Starts ejabberd jabber server, an XMPP
#                    compliant server written in Erlang.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
EJABBERDCTL=/usr/local/sbin/ejabberdctl
EJABBERDRUN=/usr/local/var/run/ejabberd
EJABBERDLOG=/usr/local/var/log/ejabberd
EJABBERDCONF=/usr/local/etc/ejabberd
EJABBERDUSER=ejabberd
NAME=ejabberd

test -f $EJABBERDCTL || exit 0

# Include ejabberd defaults if available
if [ -f /usr/local/etc/default/ejabberd ] ; then
    . /usr/local/etc/default/ejabberd
fi

ctl()
{
    action="$1"
    su -l -s /bin/sh -c "$EJABBERDCTL $action" $EJABBERDUSER >/dev/null
}

dirs()
{
    if [ ! -d $EJABBERDRUN ]; then
        mkdir -p $EJABBERDRUN
        if [ $? -ne 0 ]; then
            echo -n " failed"
            return
        fi
    fi
    ## Run Dir
    chmod -R 700 $EJABBERDRUN
    chown ejabberd:ejabberd $EJABBERDRUN
    ## Log Dir
    chmod -R 775 $EJABBERDLOG
    chown -R ejabberd:ejabberd $EJABBERDLOG
    ## Conf Dir
    chmod -R 775 $EJABBERDCONF
    chown -R ejabberd:ejabberd $EJABBERDCONF
}

start()
{
    dirs
    cd /usr/local/var/lib/ejabberd
    su -l -s /bin/sh -c "$EJABBERDCTL start" $EJABBERDUSER
    cnt=0
    while ! (ctl status || test $? = 1) ; do
	echo -n .
	cnt=`expr $cnt + 1`
	if [ $cnt -ge 60 ] ; then
	    echo -n " failed"
	    break
	fi
	sleep 1
    done
}

stop()
{
    if ctl stop ; then
	cnt=0
	sleep 1
	while ctl status || test $? = 1 ; do
	    echo -n .
	    cnt=`expr $cnt + 1`
	    if [ $cnt -ge 60 ] ; then
		echo -n " failed"
		break
	    fi
	    sleep 1
	done
    else
	echo -n " failed"
    fi
}

live()
{
    dirs

    echo '*******************************************************'
    echo '* To quit, type q().                                  *'
    echo '*******************************************************'
    echo

    cd /usr/local/var/lib/ejabberd/
    su -l -s /bin/sh -c "$EJABBERDCTL live" $EJABBERDUSER
}

case "$1" in
    start)
	echo -n "Starting jabber server: $NAME"
	if ctl status ; then
	    echo -n " already running"
	else
	    start
	fi
    ;;
    stop)
	echo -n "Stopping jabber server: $NAME"
	if ctl status ; then
	    stop
	else
	    echo -n " already stopped"
	fi
    ;;
    restart|force-reload)
	echo -n "Restarting jabber server: $NAME"
	if ctl status ; then
	    stop
	    start
	else
	    echo -n " is not running. Starting $NAME"
	    start
	fi
    ;;
    live)
	if ctl status ; then
	    echo -n "ejabberd is already running"
	else
	    live
	fi
    ;;
    *)
	echo "Usage: $0 {start|stop|restart|force-reload|live}" >&2
	exit 1
    ;;
esac

if [ $? -eq 0 ]; then
    echo .
else
    echo " failed."
fi

exit 0

